name: Generate Pacman Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:       # allows manual trigger

permissions:
  contents: write   # 👈 important

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: naein19   # 👈 your username
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generated Pacman contribution graph"
          new_branch: output
          add: "dist/*"
